FROM gitpod/workspace-full-vnc
COPY target/testing/x86_64/antlr4-4.7.2-r0.apk           antlr4-4.7.2-r0.apk
#COPY target/testing/x86_64/antlr4-dev-4.7.2-r0.apk       antlr4-dev-4.7.2-r0.apk
#COPY target/testing/x86_64/fast-0.0.8-r0.apk             fast-0.0.8-r0.apk
#COPY target/testing/x86_64/flatbuffers-1.10.0-r0.apk     flatbuffers-1.10.0-r0.apk
#COPY target/testing/x86_64/flatbuffers-dev-1.10.0-r0.apk flatbuffers-dev-1.10.0-r0.apk
#COPY target/testing/x86_64/gumtree-2.1.0-r0.apk          gumtree-2.1.0-r0.apk
#COPY target/testing/x86_64/protobuf-3.6.1-r1.apk         protobuf-3.6.1-r1.apk
#COPY target/testing/x86_64/srcSlice-1.0-r0.apk           srcSlice-1.0-r0.apk
#COPY target/testing/x86_64/srcSlice-dev-1.0-r0.apk       srcSlice-dev-1.0-r0.apk
#COPY target/testing/x86_64/srcml-0.9.5-r0.apk            srcml-0.9.5-r0.apk
#COPY target/testing/x86_64/srcml-dev-0.9.5-r0.apk        srcml-dev-0.9.5-r0.apk
RUN cd / && tar xvf antlr4-4.7.2-r0.apk
#RUN apt-get install parallel jq
#bash git openjdk8 coreutils perl jq make gcc g++ gdb libgit2-dev libxml2-dev sqlite-dev python3-dev libxml2-dev libxslt-dev python3 py3-pip python3-dev
#RUN pip3 install protobuf flatbuffers tqdm bs4 urllib3
#RUN pip3 install sklearn tensorboardX scipy numpy torch lxml 
